### ISSUE TITLE
Fails with babel-runtime

### ISSUE THREAD

**Issue by otbe** [dougmoscrop/serverless-plugin-include-dependencies#3]
Hi,

I use "serverless-plugin-include-dependencies" in conjunction with a babel project. So I include ```babel-polyfill``` which requires ```babel-runtime```. 

The plugin fails at packaging with this error:
```
Error: Cannot find module 'babel-runtime' from '...project/node_modules/ba
bel-polyfill'
    at Function.module.exports [as sync] (...project/node_modules/resolve/
lib/sync.js:36:11)
    at Object.keys.forEach.dependency (...project/node_modules/serverless-
plugin-include-dependencies/get-dependency-list.js:60:29)
....
```

I think the problem is that ```babel-runtime``` is not resolvable via ```resolve``` because of no "main" property. So this [line](https://github.com/dougmoscrop/serverless-plugin-include-dependencies/blob/master/get-dependency-list.js#L59) will raise the error above. 

Whats the correct behavior?

Thank you!

Edit: As of now I use ```babel-preset-env``` and all my problems went away :)

**Comment by dougmoscrop** [comment]
I will take a look, thanks for the info!

**Comment by aymericbeaumet** [comment]
Faced the same issue, and couldn't manage to force it through `include`. Any input?

Maybe this could be configurable with a flag.

**Comment by dougmoscrop** [comment]
I will take a look I'm just on vacation right now. Back on Monday and it's
the first thing I plan to look at. Otherwise happy for a PR that adds some
kind of override or whatever.

**Comment by aymericbeaumet** [comment]
No worries. Just found about the problem, will try to find some time to dig it.

**Comment by nbransby** [comment]
Any luck with this?

**Comment by jaypeng2015** [comment]
Faced the same issue with babel-register:

```
Cannot find module 'babel-runtime' from .../node_modules/babel-register'
```

Node: v4.3.2
```
"dependencies": {
    ...
    "babel-preset-env": "^1.1.8",
    "babel-register": "^6.18.0",
    ...
  }
```

**Comment by dougmoscrop** [comment]
Yes this needs some browserify-esque import directive. I've been swamped I
promise I will look at it soon

**Comment by dougmoscrop** [comment]
I've published v1.2.2 that should fix this and requires no additional configuration.

**Comment by boazdejong** [comment]
Unfortunately I'm still getting the exact same error with version 2.0.0.

**Comment by dougmoscrop** [comment]
I thought I wrote a test specifically for babel runtime.. stack trace is
the same above?

**Comment by boazdejong** [comment]
I'm currently getting this error when running my lambda, but was getting it earlier about `babel-runtime`

```
Unable to import module 'build/handler': Error
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/gql-merge/dist/index.js:9:16)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

Without the plugin everything works as expected.

**Comment by dougmoscrop** [comment]
I've made some changes can you try to repro with 2.1?

**Comment by boazdejong** [comment]
Not sure what project I was using this on. But I'll try to figure it out tomorrow.

**Comment by dougmoscrop** [comment]
We're using this library in a dozen or so projects with varying dependencies and I'm pretty sure I fixed this -- so I am going to close for housekeeping, but please re-open if you can still get it to happen. Thanks!
